In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [5]:
from proj1_helpers import *
DATA_TRAIN_PATH = '../resources/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)


In [2]:
%run pre_processing.ipynb
(tx_1,y_1,ids_1), (tx_2,y_2,ids_2), (tx_3,y_3,ids_3) = process_data()

## Do your thing crazy machine learning thing here :) ...

In [7]:
#Processed data 
import implementations as imp
imp.least_squares(y_1,tx_1)

(array([[-1.00860441e-03],
        [-1.21874815e-02],
        [-5.90524458e-03],
        [-5.23601149e-03],
        [ 2.40462370e-01],
        [-2.80267157e-03],
        [-5.97550108e-01],
        [ 8.28673369e-02],
        [-1.04324188e-03],
        [-1.48350075e-03],
        [ 2.78495791e-02],
        [ 6.10016648e-03],
        [-7.68336306e-04],
        [ 6.45916849e-03],
        [-3.03356215e-03],
        [ 1.33949164e-04]]),
 0.2838710703241567)

In [8]:
#Unprocessed data
imp.least_squares(y,tX)

(array([ 8.03494347e-05, -7.20202267e-03, -6.05417273e-03, -5.47559076e-04,
        -1.93874684e-02,  4.73451612e-04, -2.60379057e-02,  3.25106299e-01,
        -3.80780033e-05, -2.72780662e+00, -2.21220141e-01,  9.50794096e-02,
         6.40351602e-02,  2.73606629e+00, -3.31801117e-04, -9.54325138e-04,
         2.74082304e+00, -5.34165238e-04,  9.73498871e-04,  3.69225050e-03,
         3.54487201e-04, -5.43344615e-04, -3.30448036e-01, -1.40800497e-03,
         8.31432856e-04,  1.02117274e-03, -1.68047418e-03, -5.83664781e-03,
        -1.11088002e-02,  2.72826655e+00]),
 0.3396868094770356)

In [9]:
#Processed data 
imp.ridge_regression(y_1,tx_1,0.003)

(array([[-1.05405744e-03],
        [-1.23270721e-02],
        [-5.46545084e-03],
        [-5.13551130e-03],
        [ 2.15866884e-01],
        [-1.30090872e-03],
        [-5.31041756e-01],
        [ 8.31905517e-02],
        [-1.01567107e-03],
        [-1.53180303e-03],
        [ 2.43216589e-02],
        [ 6.09178717e-03],
        [-7.16633910e-04],
        [ 6.09128143e-03],
        [-3.07219144e-03],
        [ 1.03801311e-04]]),
 0.2839931470796199)

In [10]:
#Unprocessed data
imp.ridge_regression(y,tX,0.003)

(array([ 9.05917813e-05, -7.29992050e-03, -5.80087143e-03, -6.94660865e-04,
        -2.14113312e-02,  4.78606809e-04, -2.62144350e-02,  3.04921175e-01,
        -4.03931843e-05,  5.25494811e-03, -2.11080473e-01,  9.50323954e-02,
         6.50281371e-02,  3.03312275e-03, -3.37453778e-04, -9.90775214e-04,
         7.36770491e-03, -5.26760151e-04,  9.59230079e-04,  3.78441243e-03,
         3.57545363e-04, -5.60991720e-04, -3.06197134e-01, -1.17788633e-03,
         6.96388610e-04,  9.00367072e-04, -1.54352163e-03, -5.41822576e-03,
        -1.04797298e-02, -5.00915125e-03]),
 0.33973480318269905)

In [12]:
#Processed data 
imp.least_squares_SGD(y_1,tx_1,np.zeros(tx_1.shape[1]),1,20,0.7)

(array([[ 1.14027486e+87,  1.14027486e+87,  1.14027486e+87,
          1.14027486e+87,  1.14027486e+87,  1.14027486e+87,
          1.14027486e+87,  1.14027486e+87,  1.14027486e+87,
          1.14027486e+87,  1.14027486e+87,  1.14027486e+87,
          1.14027486e+87,  1.14027486e+87,  1.14027486e+87,
          1.14027486e+87],
        [ 1.01914280e+87,  1.01914280e+87,  1.01914280e+87,
          1.01914280e+87,  1.01914280e+87,  1.01914280e+87,
          1.01914280e+87,  1.01914280e+87,  1.01914280e+87,
          1.01914280e+87,  1.01914280e+87,  1.01914280e+87,
          1.01914280e+87,  1.01914280e+87,  1.01914280e+87,
          1.01914280e+87],
        [ 9.00779029e+86,  9.00779029e+86,  9.00779029e+86,
          9.00779029e+86,  9.00779029e+86,  9.00779029e+86,
          9.00779029e+86,  9.00779029e+86,  9.00779029e+86,
          9.00779029e+86,  9.00779029e+86,  9.00779029e+86,
          9.00779029e+86,  9.00779029e+86,  9.00779029e+86,
          9.00779029e+86],
        [ 1.6998279

In [13]:
#Unprocessed data
imp.least_squares_SGD(y,tX,np.zeros(tX.shape[1]),1,20,0.7)

(array([ 3.11917137e+116,  1.16826325e+116,  1.53717347e+116,
         6.92795020e+116,  8.55936218e+114,  8.79760124e+116,
        -4.54196236e+114,  4.19562700e+114,  9.00005238e+115,
         1.10299605e+117,  7.91979546e+114,  5.44478485e+114,
         3.44061379e+114,  1.05486722e+116,  4.63506399e+113,
         3.69275572e+114,  2.12675172e+116, -7.26800722e+113,
        -3.26099442e+113,  4.10930870e+116,  1.23355162e+114,
         1.63090369e+117,  1.17852994e+115,  3.98963120e+116,
        -3.50878444e+114,  1.21303079e+115,  2.60619418e+116,
         5.07091355e+114, -1.02224767e+115,  7.84834159e+116]),
 7.831941152648439e+239)

## Generate predictions and save ouput in csv format for submission:

In [10]:
DATA_TEST_PATH = '' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [31]:
OUTPUT_PATH = '' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)